spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.219.115:3306/permissionauthentication?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: cxn
    password: 2001101025Cxn!
  redis:
    host: 101.43.219.115
    port: 6379

  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: school-server
          uri: lb://institutions
          predicates:
            - Path=/api/institutions/**
        - id: authen-server
          uri: lb://authen-service
          predicates:
            - Path=/gateway/authen/**


server:
  port: 88

mybatis-plus:
  mapper-locations: classpath*:/xml/**/*.xml