spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.219.115:3306/permissionauthentication?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: cxn
    password: 2001101025Cxn!
  redis:
    host: 101.43.219.115
    port: 6379
  application:
    name: authen-service
  cloud:
    nacos:
      server-addr: localhost:8848

server:
  port: 8441

mybatis-plus:
  mapper-locations: classpath*:/xml/**/*.xml


